# Leitura de chave inexistente
READ [c1]
# Criacao e escrita de 2 chaves
WRITE [(c1,v1)(chave2,valor-exemplo)]
# Leitura de chave existente
READ [chave2]
# Escrita de uma chave nova e outra existente
WRITE [(chave2,valor-exemplo2)(umaChave,umValor)]
# backup
BACKUP
# Eliminacao de chave existente e de chave nao existente
DELETE [c1,chaveAleatoria]
# Espera de um segundo
WAIT 1000
# Impressao de toda a tabela
SHOW
